# Generated by Django 4.2 on 2023-05-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
